baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
[params]
    customCSS = ["css/custom.css"]
    defaultTheme = "light"
    disableThemeToggle = true
    